export enum MainActionsTypes {
    TO_BURN = '@@MAIN/TO_BURN',
    TO_BURN_SUCCESS = '@@MAIN/TO_BURN_SUCCESS',
    TO_BURN_FAILURE = '@@MAIN/TO_BURN_FAILURE',
    VIEW_FOUND = '@@MAIN/VIEW_FOUND',
    VIEW_FOUND_SUCCESS = '@@MAIN/VIEW_FOUND_SUCCESS',
    VIEW_FOUND_FAILURE = '@@MAIN/VIEW_FOUND_FAILURE',

    SET_FOUND = '@@MAIN/SET_FOUND',


}
