name: Build and Package .dapp

on:
  push:
    branches:
      - master
      - 26-add-build-workflow
      - doggy
  pull_request:
    branches:
      - master
      - 26-add-build-workflow
      - doggy

jobs:
  build:
    uses: ticotipme/Burn/.github/workflows/make-dapp.yaml@master
    with:
      manifest_name: 'doggy Burn'
      manifest_description: 'woof'
      manifest_version_prefix: "1.0"
      manifest_guid: '705c702aa7f64bc986f4d60e68243204'
      dapp_name: 'doggy-burn'
